services:

  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://postgres:secret@db:5432/kakdb
      - SECRET_KEY=e3c54bbdf281007a7fcc323f957a09b766be7bf41b265819f65ebed4405004f3
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    depends_on:
      - db

  db:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kakdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: